dropItemsOnDeath: true
nsfw-censorship:
  # default clothes for the player if they don't have any (must be at the end of the file)
  top_default_keyword: "!td="
  bottom_default_keyword: "!bd="
defaultClothes:
  hat: crown
  chestplate: gr_jacket
  trousers: cargo
  boots: kraduli
hats:
  - name: Crown
    file_name: crown
    material: GOLDEN_HELMET
    craft:
      2: GOLD_INGOT
      4: GOLD_INGOT
      6: GOLD_INGOT
      8: GOLD_INGOT
chestplates:
  - name: Green Jacket
    file_name: gr_jacket
    material: GREEN_LEATHER_CHESTPLATE
    craft:
      1: LEATHER
      3: LEATHER
      4: LEATHER
      5: GREEN_DYE
      6: LEATHER
      7: LEATHER
      8: LEATHER
      9: LEATHER
trousers:
  - name: Cargo Pants
    file_name: cargo
    material: GREEN_LEATHER_LEGGINGS
    craft:
      1: LEATHER
      2: LEATHER
      3: LEATHER
      4: LEATHER
      5: GREEN_DYE
      6: LEATHER
      7: LEATHER
      9: LEATHER
boots:
  - name: Fancy Boots
    file_name: kraduli
    material: GOLDEN_BOOTS
    craft:
      4: LEATHER
      6: LEATHER
      7: STRING
      8: STRING
